global:
  scrape_interval: 15s
  evaluation_interval: 15s

otlp:
  promote_resource_attributes:
    - service.name

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
