// <auto-generated />
using System;
using Aiyara.Report.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aiyara.Report.Databases.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    [Migration("20261006162212_AddReportFoundation")]
    partial class AddReportFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aiyara.Report.Models.ReportDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Kind", "Format")
                        .IsUnique();

                    b.ToTable("report_definitions", (string)null);
                });

            modelBuilder.Entity("Aiyara.Report.Models.ReportObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsExternallySigned")
                        .HasColumnType("boolean");

                    b.Property<long>("LengthBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ReportRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RetainUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ReportRunId");

                    b.HasIndex("TenantId", "ObjectKey", "Version")
                        .IsUnique();

                    b.ToTable("report_objects", (string)null);
                });

            modelBuilder.Entity("Aiyara.Report.Models.ReportRetentionPolicy", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Years")
                        .HasColumnType("integer");

                    b.HasKey("TenantId");

                    b.ToTable("report_retention_policies", (string)null);
                });

            modelBuilder.Entity("Aiyara.Report.Models.ReportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SubjectUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PeriodEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReportDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "ReportDefinitionId");

                    b.HasIndex("TenantId", "SubjectUserId", "CreatedAtUtc");

                    b.HasIndex("TenantId", "Status", "CreatedAtUtc");

                    b.ToTable("report_runs", (string)null);
                });

            modelBuilder.Entity("Aiyara.Report.Models.ReportSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastFireAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly>("LocalTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime?>("NextFireAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReportDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ReportDefinitionId")
                        .IsUnique();

                    b.ToTable("report_schedules", (string)null);
                });

            modelBuilder.Entity("Aiyara.Report.Models.ReportSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReportRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ReportRunId")
                        .IsUnique();

                    b.ToTable("report_snapshots", (string)null);
                });

            modelBuilder.Entity("Aiyara.Report.Models.ReportObject", b =>
                {
                    b.HasOne("Aiyara.Report.Models.ReportRun", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ReportRunId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Aiyara.Report.Models.ReportRun", b =>
                {
                    b.HasOne("Aiyara.Report.Models.ReportDefinition", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ReportDefinitionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Aiyara.Report.Models.ReportSchedule", b =>
                {
                    b.HasOne("Aiyara.Report.Models.ReportDefinition", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ReportDefinitionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Aiyara.Report.Models.ReportSnapshot", b =>
                {
                    b.HasOne("Aiyara.Report.Models.ReportRun", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ReportRunId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
