<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>72a5d2bd-a81d-462b-a1b1-7b62bd0bd5c9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="Scalar.Aspire" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Backend\gateways\Aiyara.Gateways.Api\Aiyara.Gateways.Api.csproj" />
    <ProjectReference Include="..\..\Backend\identities\Aiyara.Identities.Api\Aiyara.Identities.Api.csproj" />
    <ProjectReference Include="..\..\Backend\reports\Aiyara.Report.Api\Aiyara.Report.Api.csproj" />
    <ProjectReference Include="..\..\Backend\timesheet\Aiyara.Timesheet.Api\Aiyara.Timesheet.Api.csproj" />
  </ItemGroup>

</Project>
