<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="Autofac.Extras.DynamicProxy" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" />

    <PackageReference Include="Paseto.Core" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Scalar.AspNetCore.Swashbuckle" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aiyara.Timesheet.Componenet.Data\Aiyara.Timesheet.Component.Data.csproj" />
  </ItemGroup>

</Project>
