<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <ProjectReference Include="..\Aiyara.Identities.Databases\Aiyara.Identities.Databases.csproj" />
    <ProjectReference Include="..\..\contracts\Aiyara.Timesheet.Contracts\Aiyara.Timesheet.Contracts.csproj" />
  </ItemGroup>
</Project>
